### PR TITLE
Make jewelry with any metal without needing new defs

### PR DESCRIPTION
**Pull request by divineDerivative**
I had some ideas about improving the mod, and... I may have gotten carried away. Main feature is that jewelry can now be made with any metal/gem combination without requiring new defs for every metal.

### Two color texture masks
This allows both the metal and the gemstone to color the item. I accomplished this by adjusting the brightness and contrast of the silver textures, which I had originally made by adjusting the saturation of the gold textures. The mask is then switched so the metal is color one and the gemstone is color two.

### New thing class, `JewelryThing`
Inherits from `Apparel`, this stores the gemstone and overrides several methods to add the gemstone in various places.
- The `Stuff` is now the metal instead of the gemstone.
- Both the metal and the gemstone can be returned when smelting jewelry.
- Label includes both the metal and the gemstone.
- Gemstone is displayed on the info card after stuff.

### Recipe worker
Added an empty recipe worker class, `RecipeWorker_Jewelry`. This is just to easily target the correct recipes when needed:
- To make a dictionary of which `ThingDef` belongs to each `RecipeDef`.
- In a postfix to `GenRecipe.MakeRecipeProducts` to save the gemstone used and ensure the metal is set as the stuff.

Also moved the recipes to their own defs instead of as a `recipeMaker` on the thing defs, simply because I found that easier to work with.

### Consolidation
- Removed the silver jewelry defs since they are no longer needed.
- Removed duplication of patches and defs for 1.4 vs 1.5 since the differences are minimal and can be solved with `IgnoreIfNoMatchingField`. I think they can actually share assemblies as well but haven't tested that extensively.
- This does break the mod for 1.3 and below, but I'm sure I can fix that, either with LoadFolders or further consolidation. I just didn't want to do a bunch of work for no reason, if you're not interested in this update.
- Put more of the xml in abstract bases, so it's easier to change something and not have to remember to change it everywhere.
- Where possible, put conditional things directly in the defs using `MayRequire` instead of using patches so it's easier to see all the info in one place.
- Put similar defs in one file, simply my own preference.

### Back compatibility
Two patches to back compatibility functions to convert old jewelry to the new format when loading a save file.
- Any jewelry with the `Apparel` thing class will be changed to `JewelryThing`.
- The old stuff will be added as the gemstone and the metal will be inferred from the defName, to be set as the new stuff.
- Old silver jewelry will then have the defName changed.

### CODE REVIEW

**Comment by juanosarg** [comment]
What do you mean "removed defs". You can't do that without bricking saves :)

**Comment by divineDerivative** [comment]
That's what the back compatibility is for. It intercepts reading the old defs from the save file and converts them to the new one.

**Comment by juanosarg** [comment]
Ahhh, hadn't seen the patch. Ok, I'll ask Kikohi if he is OK with us adding new things to the mod

**Comment by juanosarg** [comment]
Just pushed this!

**Pull request merged**
